### ISSUE TITLE
`nbpdfexport` dependency incorrect

### ISSUE THREAD

**Issue by mattf1n** [ucbds-infra/nb2pdf#5]
When installing (`pip install nb2pdf`) I get the error
```
ERROR: Could not find a version that satisfies the requirement nbpdfexport==0.2.2 (from nb2pdf->otter-grader) (from versions: 0.1, 0.2, 0.2.1)
ERROR: No matching distribution found for nbpdfexport==0.2.2 (from nb2pdf->otter-grader)
```
Looks like `setup.py` requires `nbpdfexport==0.2.2`, an unreleased version of [`nbpdfexport`](https://pypi.org/project/nbpdfexport) (latest release is `0.2.1`).

**Comment by mattf1n** [comment]
Installing with `pip install git+https://github.com/eldridgejm/nb2pdf` works for now as a workaround.

**Comment by leestott** [comment]
Repo - Error 

Collecting otter-grader
  Using cached otter_grader-0.4.7-py3-none-any.whl (29 kB)
Collecting nb2pdf
  Using cached nb2pdf-0.6.1-py3-none-any.whl (7.9 kB)
Collecting tornado==5.1.1
  Using cached tornado-5.1.1.tar.gz (516 kB)
Collecting codecov
  Using cached codecov-2.1.8-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: nbformat in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from nb2pdf->otter-grader) (4.4.0)
ERROR: Could not find a version that satisfies the requirement nbpdfexport==0.2.2 (from nb2pdf->otter-grader) (from versions: 0.1, 0.2, 0.2.1)
ERROR: No matching distribution found for nbpdfexport==0.2.2 (from nb2pdf->otter-grader)

@chrispyles

**Comment by chrispyles** [comment]
Try reinstalling nb2pdf (should install as 0.6.2). This version should have the dependency issue resolve.
